name: fincra_payment
description: "A fincra checkout payment package"
version: 1.0.0
homepage: https://github.com/ayanfesolution/fincra_payment.git
repository: https://github.com/ayanfesolution/fincra_payment.git
issue_tracker: https://github.com/ayanfesolution/fincra_payment/issues
license: MIT


environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:

